defaults :
  - _self_
  - model : testmodel
  - data : CIFAR10
  - loss : testloss
  - metrics : testmetrics

experiment :
  project : pl-hydra-test
  uuid : ${now:%m%d_%H%M%S}
  save_dir : ${hydra:runtime.cwd}/logs/
  seed : 8967
  checkpoint_interval : 1000
  log_image_interval : 500

loader: 
  batch_size: 1
  num_workers: 16
  pin_memory: True

optimizer :
  lr : 1e-3

scheduler:

trainer:
  max_steps: 120001      #! epochs * steps_per_epoch
  log_every_n_steps: 50
  accelerator : 'gpu'
  devices : 4
  precision: 32

  limit_train_batches: 1.0
  limit_val_batches: 1.0
  check_val_every_n_epoch: 1
  val_check_interval: 1.0
  num_sanity_val_steps: 0
  gradient_clip_val: 5.0
  sync_batchnorm: True  #! False